### ISSUE TITLE
Survey Question on the For loop in source file https:/github.com/DiTo97/gol/blob/master/src/cpu/gol.c line 151

### ISSUE THREAD

**Issue by quazirafi** [DiTo97/gol#1]
Hello Sir/ Madam
We are from a research group at Iowa State University, USA. We want to do a survey on Github developers on the methods they used for paralleling their code. To do the survey, We want to ask three questions about this for loop:

Can you briefly explain the purpose of using pragma for this case? If the pragma contained reduction and private clauses, can you briefly mention the purposes of variables in those clauses?

How much confidence do you have about the correctness of this implementation? You can choose from 1-5 with 1 as the lowest confidence score and 5 as the highest confidence score.

(Optional) Do you actually run (interpret the code with compilation and pass input/get output) the code and see the optimization of parallelization? Yes/No

If yes, can you provide the information of what are the input and expected output of this program (the input that caused the program to run through this for-loop).
The for loop is from line 151 of file https:/github.com/DiTo97/gol/blob/master/src/cpu/gol.c
Here is a part of the code:

#pragma omp parallel for
    #endif
    for (i = 0; i < life->nrows; i++) {
        free(life->grid[i]);
        free(life->next_grid[i]);
    }

**Comment by DiTo97** [comment]
Hi,

I'm glad to help you with your survey. This program was designed as a research case study to compare the performance of large-scale Conway's Game of Life under different parallelization settings: single-thread, multi-thread with Open MP, multi-process with MPI, hybrid with Open MP+MPI and on CUDA. The program would take a text file as input specifying the size of the board, and the initial configuration of alive cells.

The specific piece of code you are referring to is called near the end of the program during cleanup ops. It takes a `life_t` object as input (you can find its definition in [life.h](https://github.com/DiTo97/gol/blob/main/include/life/life.h)) and frees up the memory allocated on a single processor for a subset or the full GoL grid depending on its size. The grid (or part of it) and its copy (necessary for update and swap ops at the end of each iteration) are allocated dynamically as 2D pointers at startup. Therefore the pointers can be freed up independently, i.e., in parallel, if multi-threading is enabled. So, we just check if the code is compiled with Open MP through the macro guard, and if that's the case we define a #pragma guard to parallelize the underlying for-loop with Open MP. The function doesn't provide any outputs.

About my confidence in the correctness of the implementation of the function, I would rate it as full a 5 out of 5, because we have tested it thoroughly, and we have noticed a noticeable speedup with Open MP enabled. I would rate the whole program as a 4 out of 5, because we did not provide a 100% test coverage due to time constraints on our deadline. 

Finally, we have observed the effect of any possibile optimization routines in the code, included this specific function. You can find an in-depth analysis in the [report](https://github.com/DiTo97/gol/tree/main/report) folder.

Hope this helps with the survey!

**Comment by quazirafi** [comment]
Thank you so much! It was really helpful. I am closing the issue. Thank you again!
